version: '3'
services:
  mysql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-users:/docker-entrypoint-initdb.d/
  server-users:
    build: ./server-users
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - MYSQLHOST=mysql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=ef79
      - TOTPSECRET=ac36
      - JWTSECRET=jwtsecret
    volumes:
      - ./server-users/backend-users:/app/backend
    ports:
      - "8001:80"
  mysql-website:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql-website:/docker-entrypoint-initdb.d/
  server-website:
    build: ./server-website
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-website
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server-website/backend-website:/app/backend
      - ./server-website/frontend:/app/frontend
    ports:
      - "80:80"
